### ISSUE TITLE
Spacing between words

### ISSUE THREAD

**Issue by ikenye** [marcreichel/alpine-typewriter#4]
Good day. It seems like there is an issue with spacing between words. I'll try to look at it in-depth tomorrow. But just a heads up. Thanks for the package through,

Input: 

 
![image](https://user-images.githubusercontent.com/121995590/211170983-1eff78de-df3e-49b2-865a-f0007c845ab8.png)

This is the end result. 

![image](https://user-images.githubusercontent.com/121995590/211170962-e9bf4785-bb97-4fc3-a63f-535d265c24c8.png)

**Comment by marcreichel** [comment]
Hi, thanks for reporting. I could not reproduce your behavior though. Could you maybe provide a little more information on your setup or build process? Perhaps the spaces get trimmed away in your setup for some reason.

**Comment by ikenye** [comment]
Good day,

Thanks for the response.

My composer.json file is as follows:

![image](https://user-images.githubusercontent.com/121995590/211257078-c0da1db7-ac3f-4782-a98e-6b3d9d668b72.png)

![image](https://user-images.githubusercontent.com/121995590/211257139-05700dee-a44a-45d2-adef-6f0d4494bce4.png)

My package.json file is as follows:

![image](https://user-images.githubusercontent.com/121995590/211257304-ff4e8ec5-dc9c-455d-ac6f-c344878de8de.png)

![image](https://user-images.githubusercontent.com/121995590/211257366-02aa44fe-b9bf-4007-8bee-72aad5cb8863.png)

My app.js file is as follows:

![image](https://user-images.githubusercontent.com/121995590/211257468-7e044f3f-0772-4e1d-8941-19b8ed65f641.png)

I hope this helps.

**Comment by marcreichel** [comment]
Thanks! I cannot see any problems in your setup. The only “difference” would be, that you're using Vite for your build process. Whereas other sites where it's working as expected still use Laravel Mix. I will try to set up a project with Vite and check if this is the issue.

**Comment by ikenye** [comment]
Good day,

Thanks for the response. I look forward to hearing back from you.

**Comment by marcreichel** [comment]
@ikenye

Hi, here's some update for you:

I've set up a new project with vite now. And I can reproduce the missing spaces between the words. So we can circle down the issue to some problem with Vite. But I'm not quite sure yet how to solve this issue. I will fiddle around a bit and keep you updated 👍🏼

**Comment by marcreichel** [comment]
A quickfix/workaround for now would be to replace the spaces by non-breaking spaces (`&nbsp;`). So `Hello World` would become `Hello&nbsp;World`. Not pretty but it works though.

**Comment by ikenye** [comment]
Thanks for the response. As long as it works, for now, that should be okay. Thanks for everything. Not too sure if you want to keep the issue open or move it elsewhere.

**Comment by Log1x** [comment]
Having this same issue using https://github.com/roots/bud for asset compilation.

**Comment by marcreichel** [comment]
@ikenye I'll keep the issue open as I want to search for a solution (or let anyone interested search for a solution) 👍🏼

**Comment by marcreichel** [comment]
@ikenye @Log1x Fixed the behavior with version [1.0.1](https://github.com/marcreichel/alpine-typewriter/releases/tag/1.0.1). Feel free to update 🙂

**Comment by ikenye** [comment]
Thanks a mill!
